name: first CI/CD

on:
  pull_request:
    branches:
      - main


jobs:
  welcome_script:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome part
        run: echo "Hello, guys 😅"
      - name: Get info
        run: |
          echo "Getting comp info...."
          whoami
          sleep 5
          pwd


  checking:
    needs: [welcome_script]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.12]
    steps:
      - uses: actions/checkout@v4
      - name: Install python ${{ matrix.python-version }}
        uses: actions/checkout@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Installing dependencies
        run: |
          if [ -f requirements.txt ]; then poetry add -r requirements.txt; fi
          poetry add flake8 black isort faker

      - name: check with linter
        run: |
          black . --check
          isort .
          flake8 .
